### ISSUE TITLE
Method for Plotting Values Needs to be Better 

### ISSUE THREAD

**Issue by djperrefort** [mwvgroup/Surface-Brightness#3]
When plotting surface brightness or the log_10 of surface brightness verses redshift, the error bars make it difficult to show all the data in a a single plot. Too small of a range hides data that begins to peak as redshift becomes smaller, but too large a range make it difficult to discern data points as redshift approaches 1.

Proposed solutions:

1) In a previous group meeting we discussed that there may be a mistake in the error propagation of the script. Afterward, I remembered that I had copied and pasted some code from a scrap file before double checking it. I realized that I had mistakenly switched the order of two objects when typing an equation for the error in log of the surface brightness. This mistake has been fixed. The fixed error bars, however, are still symmetric when I plot the log_10 of the surface brightness. This is because I am plotting the log of the value on a standard plot. This needs to be changed so that the regular values are plotted on a log scale.

2) The script will loop through all of the surface brightness values that it calculates and keep only the value with the smallest error for each supernova region. This process should be extended to show only values larger than 3 sigma in the plot.

**Comment by kponder** [comment]
Where's the code for your plotting? 

Just in case it's a plotting error, check out this [example](http://matplotlib.org/examples/pylab_examples/log_demo.html).

**Comment by djperrefort** [comment]
Thanks for the reference. I'm going to try to implement that method instead of what I'm currently doing. Right now the code I'm using is:

r = [float(i) for i in r[1:]] #A list of the redshift values
l_s = [float(i) for i in l_s[1:]] #A list of the log_10 of the surface brightness
l_s_err = [float(i) for i in l_s_err[1:]] #A list of error values corresponding to the values in l_s

ax1 = plt.subplot(111)
ax1.errorbar(r, l_s, xerr=0, yerr=l_s_err, color='black', linestyle='None')
ax1.set_ylim([32, 44])
plt.xlabel('Redshift')
plt.ylabel('log 10 of Surface Brightness')
plt.title('Supernova Region Brightness Vs. Redshift')
plt.savefig(output_file.replace('.csv',' log 10.pdf'))
plt.show()
plt.close()

**Comment by kponder** [comment]
Either do not include this keyword

`xerr=0`

or change it to 

`xerr=None`

The error is not exactly zero, you just did not calculate it. (and it may cause problems with the log scale)

**Comment by djperrefort** [comment]
I've rewritten the code and attached [an example of the output plot](https://github.com/mwvgroup/Surface-Brightness/files/301663/output.NUV.log.10.pdf). I think this new method is a lot better and the plot looks improved too. My only thought is whether or not I should keep ax.plot(r,s,'.') to include the blue points in the output plot. 

r = [float(i) for i in r[1:]] #A list of the redshift values
s = [float(i) for i in s[1:]] #A list of the surface brightness
s_err = [float(i) for i in s_err[1:]] #A list of error values corresponding to the values in s

ax = plt.gca()
ax.errorbar(r, s, xerr=None, yerr=s_err, color='black', linestyle='')
ax.plot(r, s, '.')
ax.set_yscale('log')

plt.xlabel('Redshift')
plt.ylabel('log 10 of Surface Brightness')
plt.title('Supernova Region Brightness Vs. Redshift')

plt.savefig(output_file.replace('.csv',' log 10.pdf'))
plt.show()
plt.close()

**Comment by wmwv** [comment]
Work on facility with numpy arrays and thinking about array-based operations.  E.g., you should be able to replace

```
r, s, s_err = [], [], []
    
for row in out_unique: 
    r.append(row[1])
    s.append(row[12])
    s_err.append(row[13])
```

with 

```
r = out_unique[1]
s = out_unique[12]
s_err = out_unique[13]
```

If this doesn't work directly, then rework your construction of out_unique so that it does.

Similarly,

```
r = [float(i) for i in r[1:]] #A list of the redshift values
s = [float(i) for i in s[1:]] #A list of the surface brightness
s_err = [float(i) for i in s_err[1:]] #A list of error values corresponding to the values in s
```

could be re-written as
```
r = r[1:]
s = s[1:]
s_err = s_err[1:]
```

and if r, s, s_err are not yet np.arrays you could cast them as such and say
```
r = np.array(r[1:])
s = np.array(s[1:])
s_err = np.array(s_err[1:])
```

**Comment by wmwv** [comment]
More generally I would suggest you switch to using AstroPy tables instead of a np.array of lists.

**Comment by djperrefort** [comment]
Originally I had used 

`r = [float(i) for i in r[1:]]`

instead of just

`r = r[1:]`

because the values in r were strings and I needed floats. I will switch to AstroPy so that the columns will already have the correct data type, making this step unnecessary.

**Comment by wmwv** [comment]
```
r = np.array(r[1:], dtype=float)
```

**Comment by djperrefort** [comment]
I didn't think to use additional arguments with np.array - that makes things a lot simpler. Thank you!
