### ISSUE TITLE
Plot surface brightness per kpc and clearly state on axis labl.

### ISSUE THREAD

**Issue by wmwv** [mwvgroup/Surface-Brightness#5]
Surface brightness of NUV or FUV luminosity / kpc is the thing that should be physically constant for the equivalent galaxy at different redshifts.  Make these plots in addition to the current luminosity/arcmin^2 plots (and change those to /arcsec^2).  Clearly label the yaxis of each with the units to make it immediately clear which is being plotted.

**Comment by djperrefort** [comment]
I've added a plots in units of erg / s / A / Arcsecond^2 and erg / s / A / kpc^2. I'm not sure why the error bars are so large, but I'm working on this next.
