### ISSUE TITLE
Make output table units agree with `photometry` results.  Check consistency of units and calculation.

### ISSUE THREAD

**Issue by wmwv** [mwvgroup/Surface-Brightness#6]
`photometry` returns counts / pi / kpc^2

`flux` is then defined to be erg / s / cm^2 / Angstrom / pi / kpc^2

But the Table lists units of
'Flux (erg s-1 cm-2 A-1 px-1)'
'Luminosity (erg s-1 A-1 px-1)'
'Surface Brightness (erg s-1 A-1 Kpc^-2)'

which I don't think are consistent with how they are being calculated in the main code loop.  Flux and Luminosity are listed as being / pixel, while Surface Brightness is listed as / kpc^2, when I believe it's / arcmin^2.

**Comment by djperrefort** [comment]
I will go through the main code loop and work out the correct units and fix the table. Since the .fits image gives values of counts per second, shouldn't `photometry` return values of counts / pi / kpc^2 / s ?

**Comment by wmwv** [comment]
Yes, sorry.  I agree that `photometry` returns 'counts / s / pi / kpc^2'

**Comment by djperrefort** [comment]
Since the surface brightness is no longer being calculated from a single pixel, flux is no longer in terms of per pixel. This means calculating surface brightness as

    sbrightness = (lum / pixel_area) * arcmin 

is incorrect. It should instead be 

    sbrightness = lum * arcmin 

followed by a conversion from arc minutes to arc seconds.

**Comment by djperrefort** [comment]
As of the last commit (583ef48):

 `photometry` returns a value in counts / s / pi / kpc^2.

`Flux` is found by using the appropriate conversion factor given by [Galex] (http://asd.gsfc.nasa.gov/archive/galex/FAQ/counts_background.html). This conversion factory has units of erg / counts / cm^2 / A so `flux` has units of erg / cm^2 / A /  s / kpc^2

To find the `Luminosity` we multiply by the surface area of a sphere (using luminosity distance) in cm^2 which gives erg / A /  s / kpc^2 

`Surface brightness` is can be found per arcsec^2 by multiplying by `cosmo.kpc_comoving_per_arcmin(redshift).value` and converting from arcmin^2 to arcsec^2. This leaves us with erg / s / A / Arcsecond^2.
