### ISSUE TITLE
Use astropy.units to store units in units; Remove units from column names

### ISSUE THREAD

**Issue by wmwv** [mwvgroup/Surface-Brightness#8]
See https://github.com/mwvgroup/nir_host_galaxy/issues/7
for an example of including units.

**Comment by djperrefort** [comment]
As part of this issue I wanted to change the output file format from .csv to .fits, but encountered an issue where astropy cannot write a table to a .ftis file if the table has a column with `dtype = object`. I am adding a link to this issue as a reference: https://github.com/astropy/astropy/issues/1906.

**Comment by wmwv** [comment]
This behavior by the AstroPy FITS writer seems correct.  It certainly can't serialize arbitrary objects.  But neither can .csv.

What is the object in this case?

**Comment by wmwv** [comment]
The one difference that I know about and that astropy/astropy#1906 is reporting, is the case of "None".  CSV will serialize that to '--'.  Whereas FITS will not (and should not).  It's often possible that one may mean to write "None"s out as "NaN".

**Comment by wmwv** [comment]
@djperrefort What's the simplest example that recreates the error for your purposes?

**Comment by djperrefort** [comment]
I originally had a table with `dtype = [object, ... ]` and this error was raised. The error can be reproduced by running the following.

    from astropy.table import Table
    t = Table(names = ['col_name'], dtype = [object])
    t.add_row(['abc'])
    t.write('test_file.fits', format='fits')

I had originally used `dtype = [object]` because my first column contained strings and `dtype = [str]` or `dtype = [unicode]` will only retain the first letter of `'abc'` in the row entry and I didn't want to have to specify the length of the string by using something like `dtype = ['a64']`.

**Comment by wmwv** [comment]
You have to specify the length of the string.  FITS binary tables are constructed with a fixed number of bytes for each column (fixed when written).  This known pattern allows for rapid calculation of offsets and slicing by rows.  But it means that the byte-size of each column needs to be known and fixed.

In Python everything is an `object`, so specifying `dtype=object` works, but it's not particularly informative.

* Nice test case.

**Comment by djperrefort** [comment]
In order to avoid this issue I've switched to using `dtype = ['S70']`.

**Comment by djperrefort** [comment]
The units `erg` and `Angstrom` have both been depreciated in the fits standard but are still currently supported. Do you have a preference as to whether or not I should decompose the units or leave them in terms of `angstrom` and `erg`?

**Comment by wmwv** [comment]
Please keep as `Angstrom` and `erg`.
