### ISSUE TITLE
Not performing photometry at all coordinates

### ISSUE THREAD

**Issue by djperrefort** [mwvgroup/Surface-Brightness#9]
The `photometry` function will loop through a list of coordinates and perform photometry on the first coordinate that falls on the fits image. After performing photometry, however, it fails to check any of the remaining coordinates in the list.

**Comment by djperrefort** [comment]
I have changed the code so that all coordinates are checked for each .fits file. I thought these changes would be enough to resolve this issue, but when I ran a test case there was one file that returned a negative photometry value. I believe this is because the counts in the `skybg` file are larger than those in the `int` file, but I have not verified this. Relevant code:

    #Subtract the skybg file
    sky_subtracted = int_file
    sky_subtracted[0].data = int_file[0].data - skybg_file[0].data
    phot_table = aperture_photometry(sky_subtracted[0], aperture, error = error)

In the commit e467504 I have included print statements in `Surface Brightness.ipynb` to outline the photometry results returned for each .fits file. My next step is to check the `int` and `skybg` .fits files manually in ds9 and see if the results make sense.

**Comment by djperrefort** [comment]
Realized that i had forgotten to replace an instance of `int_file` with `sky_subtracted`. New code reads

    with fits.open(fits_file) as int_file:
        if os.path.isfile(fits_file.replace('d-int', 'd-skybg')):
            with fits.open(fits_file.replace('d-int', 'd-skybg')) as skybg_file:

                wcs = WCS(fits_file)
                for sn in cord:
                
                    #Define the SN location in pixels
                    w = wcs.all_world2pix(cord[sn].ra, cord[sn].dec, 1)
                    
                    #Make sure the sn is located in the image
                    if 0 < w[0] < 3600 and 0 < w[1] < 3600:
                        
                        #Subtract the skybg file
                        sky_subtracted = int_file
                        sky_subtracted[0].data = int_file[0].data - skybg_file[0].data
                        
                        #get exposure time and create an array of the error in each pixel
                        exp_time = int_file[0].header['EXPTIME']
                        error = np.sqrt(sky_subtracted[0].data * exp_time) / exp_time
                        
                        #Find arcmin of a 1kpc radius region
                        r = radius * u.kpc / cosmo.kpc_comoving_per_arcmin(float(red[sn]))
                        
                        #Create an aperture
                        aperture = SkyCircularAperture(cord[sn], r)
                        
                        #Perform photometry
                        phot_table = aperture_photometry(sky_subtracted[0], aperture, error = error)

Photometry values are now all positive, but some of the error values generated by `aperture_photometry` are now `nan`. I have included print statements in the last commit (247cbad) that demonstrate the issue.

**Comment by djperrefort** [comment]
Including more fits files yields another negative case:

    fits file: fits files/Rigault 15/6383476603166392320/AIS_357_sg25-nd-int.fits
    sn: SN2008af
    photometry value: -0.00242723681783
    photometry error: nan 

fits files have been uploaded to Marduk at '/home/depot/WIYN/GALEX/fits files/Rigault 15 Supernova'

**Comment by djperrefort** [comment]
@wmwv is it incorrect to subtract a one fits file from another as

    with fits.open(fits_file) as int_file:
        with fits.open(fits_file.replace('d-int', 'd-skybg')) as skybg_file:

            sky_subtracted = int_file
            sky_subtracted[0].data = int_file[0].data - skybg_file[0].data

**Comment by wmwv** [comment]
Conceptually what you are doing seems fine.  Subtracting the data arrays of two FITS objects when  those data arrays are of the same size and refer to the same region of sky should definitely work.

But I assume you ask because something is not working.

Is it the case that the `skybg_file[0].data` array is the same size as the `int_file[0].data` array?

**Comment by djperrefort** [comment]
The array's both have the same shape `(3840, 3840)`. I thought that a manipulation of the header attributes might be required when subtracting fits files and that the lack of this manipulation is why `photutils.aperture_photometry ` is returning `nan` as an error value, but this appears to be false. I also thought that the `sky_subtracted[0].data` might have negative values in the array, but

    True in sky_subtracted[0].data < 0

 returns as `False` so I'm not sure why I'm getting `nan`.

**Comment by wmwv** [comment]
1. I think it's totally reasonable that you will occasionally get a negative value.
2. Trace the errors correctly.  If you are subtracting two numbers, than the error on the resulting
number is the quadrature sum of the errors on the two numbers.

**Comment by djperrefort** [comment]
I have modified the error propagation to fix my previous mistake:

    exp_time = int_file[0].header['EXPTIME']
    int_error = np.sqrt(int_file[0].data * exp_time) / exp_time
    skybg_error = np.sqrt(skybg_file[0].data * exp_time) / exp_time
    subtracted_error = np.sqrt(int_error**2 + skybg_error**2)

While my error propagation was clearly wrong, it does not seem to be the source of this issue since some photometry errors are still reported as `nan`.

**Comment by djperrefort** [comment]
The nan comes from taking the square root of a negative number. We can avoid this by performing photometry on the int and skybg files before subtracting the skybg contribution.

    #Find arcmin of a 1kpc radius region
    r = 1 * u.kpc / cosmo.kpc_comoving_per_arcmin(redshift)
    
    #Create an aperture
    aperture = SkyCircularAperture(cord, r)
    
    #get exposure time and create an arrays of the error in each pixel
    exp_time = int_file[0].header['EXPTIME']
    int_error = np.sqrt(int_file[0].data * exp_time) / exp_time
    skybg_error = np.sqrt(skybg_file[0].data * exp_time) / exp_time
    
    #Perform photometry on each .fits file
    int_phot_table = aperture_photometry(int_file[0], aperture, error = int_error)
    skybg_phot_table = aperture_photometry(skybg_file[0], aperture, error = skybg_error)
    
    #Subtract the skybg contribution
    photometry_sum = int_phot_table[0][0] - skybg_phot_table[0][0]
    photometry_error = np.sqrt(int_phot_table[0][1]**2 + skybg_phot_table[0][1]**2)

When comparing this with the previous method we get slightly different photometry results. For SN2007if, performing photometry after subtracting the array's gives 0.00175331540504, while performing photometry first gives 0.00175331540318. Fortunately the difference between these results is much smaller than the error 0.00184631624515.
